

services:
  app:
    build: .
    container_name: app-1000meal
    ports:
      - "8080:8080"

    env_file:
      - .env

    environment:

      # ðŸ”’ JPA ìž ê¸ˆ
      SPRING_DATASOURCE_URL: jdbc:mysql://soonbob-db.cneoikiukcul.ap-northeast-2.rds.amazonaws.com:3306/1000meal_test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=utf8
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 242f4NLz

      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_SQL_INIT_MODE: never

      # Flyway (ìµœì†Œ ì„¤ì •)
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_LOCATIONS: "classpath:db/migration"
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
      SPRING_FLYWAY_BASELINE_VERSION: "3"
      SPRING_FLYWAY_CREATE_SCHEMAS: "false"

      LOGGING_LEVEL_org_flywaydb: DEBUG

      # ê¸°íƒ€
      ACCESS_KEY: ${ACCESS_KEY}
      SECRET_KEY: ${SECRET_KEY}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      FCM_SERVICE_ACCOUNT_BASE64: ${FCM_SERVICE_ACCOUNT_BASE64}



    restart: "no"

    logging:
      driver: awslogs
      options:
        awslogs-region: ${AWS_REGION}
        awslogs-group: ${CW_LOG_GROUP}
        awslogs-create-group: "true"



volumes:
  mysql-1000meal-data:
