

services:
  app:
    build: .
    container_name: app-1000meal
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=utf8
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
#      DB_HOST: ${DB_HOST}
#      DB_USERNAME: ${DB_USERNAME}
#      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: localhost
      DB_USERNAME: root
      DB_PASSWORD: 8024
    restart: always

volumes:
  mysql-1000meal-data:
