

services:
  app:
    build: .
    container_name: app-1000meal
    ports:
      - "8080:8080"

    env_file:
      - .env

    environment:

      # üîí JPA Ïû†Í∏à
      SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"
      SPRING_SQL_INIT_MODE: "never"
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "false"

      # üß¨ Flyway
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
      SPRING_FLYWAY_BASELINE_VERSION: "3"
      SPRING_FLYWAY_LOCATIONS: "classpath:db/migration"

      # üîç Flyway Î°úÍ∑∏
      LOGGING_LEVEL_org_flywaydb: DEBUG

      # üì¶ Datasource (Flyway/JPA Í≥µÌÜµ)
      SPRING_DATASOURCE_URL: ${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

      # Í∏∞ÌÉÄ
      ACCESS_KEY: ${ACCESS_KEY}
      SECRET_KEY: ${SECRET_KEY}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      FCM_SERVICE_ACCOUNT_BASE64: ${FCM_SERVICE_ACCOUNT_BASE64}



    restart: "no"

    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-2
        awslogs-group: /1000meal/test/app
        awslogs-create-group: "true"



volumes:
  mysql-1000meal-data:
